Provide more sandboxing options
aseriousbiz/abbot-py pull request #136
Opened 2023-03-08 20:13 UTC by analogrelay

This expands our sandboxing options and splits them in to three profiles:

1. No Sandboxing
2. "Light" Sandboxing - Assumes you're running on a relatively-sandboxed host and only does some basic filtering of environment variables (to reduce noise rather than protect resources)
3. Restrictive Sandboxing - Our current sandboxing profile, uses RestrictedPython to severely limit what scripts can do.

2023-03-08 21:49 UTC, dahlbyk requested changes

2023-03-08 21:50 UTC, analogrelay commented on src/SkillRunner/bot/policy.py
> +            policy = "permissive"
Oop, good eye. I originally called `NoPolicy` `PermissivePolicy` and just forgot to update here.

2023-03-08 22:12 UTC, dahlbyk approved these changes

2023-03-09 06:34 UTC, haacked commented
Ah, I should have [read this](https://github.com/aseriousbiz/abbot/issues/2372#issuecomment-1460743130) first. I wonder if "light" is the right name vs something like "virtualized" or "docker". Or keep it "light" but document the conditions where it might be used, such as in Docker.

2023-03-16 22:42 UTC, merged